version: 2

sources:
  - name: sap
    description: Fonte de dados da Adventure Works
    schema: sap_adw
    tables:
    - name: salesorderdetail
      columns:
        - name: rowguid
          tests: 
            - unique
            - not_null        
    - name: product
      columns: 
        - name: rowguid
          tests:
            - unique
            - not_null
    
    - name: salesperson
      columns: 
        - name: rowguid
          tests:
            - unique
            - not_null
            
    - name: employee
      columns: 
        - name: rowguid
          tests:
            - unique
            - not_null

    - name: person
      columns: 
        - name: rowguid
          tests:
            - unique
            - not_null

    - name: customer
      columns: 
        - name: customerid 
          tests:
            - unique
            - not_null
      
    
    - name: stateprovince
      columns: 
        - name: stateprovinceid
          tests:
            - unique
            - not_null
      
    - name: address
      columns: 
        - name: addressid
          tests:
            - unique
            - not_null
      
    - name: countryregion
      columns: 
        - name: countryregioncode
          tests:
            - unique
            - not_null

    - name: salesterritory
      columns: 
        - name: territoryid
          tests:
            - unique
            - not_null
      
      
            
